### ISSUE TITLE
Making it easier to find empty fields

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#10]
The red square around empty fields is only visible if the tool is opened. Instead of blanking out the next step button I think it would be appropriate to provide a field listing the steps and specific fields that needs to be filled in before progressing.

**Comment by fikipollo** [comment]
Added a more developed method for form validation. Now erroneous fields are indicated at the top of the form and at the right of each invalid input with a red exclamation symbol. Besides, the application will autofocus the first invalid field.

Added in v0.3

![screenshot_2017-09-06_13-57-53](https://user-images.githubusercontent.com/11427394/30110800-a11b912a-930b-11e7-9f03-a107943a0db4.png)
