### ISSUE TITLE
”Error while creating the form: Unknown input type section” when running Macs2 callpeak

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#11]
History available at: https://usegalaxy.org/u/tomkl/h/chip-seq-megakaryocytes
Workflow: https://usegalaxy.org/u/tomkl/w/galaksiocase
Subworkflow (import it and it should be activated by the above workflow): https://usegalaxy.org/u/tomkl/w/subworkflowgalaksiocase
When opening a step with MACS2 callpeak I get an error ”Error while creating the form: Unknown input type section”.

**Comment by fikipollo** [comment]
Added support for "section" data types

Added in v0.3
