### ISSUE TITLE
Report error button does not seem to do anything.

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#12]
Clicking the report error button does not seem to do anything.

**Comment by fikipollo** [comment]
Fixed. Upgraded the version of the "AngularJS dialogs" library (https://github.com/fikipollo/angular-dialogs) to support the Report button handler. Added settings to configure a SMTP server in Galaksio and send the error report via email to the developers account. Alternatively, if not SMTP settings are provided, the report is forwarded to a main Galaksio server which will send the report by email.

Added in v0.3
