### ISSUE TITLE
Moving back when fields are missing makes it impossible to reach the page to fill in the fields

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#14]
Clicking previous step at the ”custom parameters” step when you have an empty field means that you cannot move forward from ”Input selection” to fill it in. Moving further back to History selection makes the button clickable but nothing happen and you need to cancel the workflow initiation and redo all steps if you want to run a workflow.

**Comment by fikipollo** [comment]
Fixed in #10 

Added in v0.3
