### ISSUE TITLE
Display label of first step for input data

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#16]
When selecting input data it would be good if the label of the first step is displayed. Because right now we have two identically named ”Input dataset collection” in the Galaksio workflow and it is not possible to differentiate them while they in Galaxy they are named 1: Control Fastq List and 2: Treatment Fastq List.

History available at: https://usegalaxy.org/u/tomkl/h/chip-seq-megakaryocytes
Workflow: https://usegalaxy.org/u/tomkl/w/galaksiocase
Subworkflow (import it and it should be activated by the above workflow): https://usegalaxy.org/u/tomkl/w/subworkflowgalaksiocase

**Comment by fikipollo** [comment]
Fixed, now the input data shows the label in the workflow +  a subtitle with the type of collection (list, pair,...)

**Comment by fikipollo** [comment]
Added in v0.3
