### ISSUE TITLE
Erroneously receive "Failed while retrieving workflows list" warning when logging in

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#2]
When logging in I get a "Failed while retrieving workflows list" warning in a pop up but all workflows are displayed properly and using the refresh workflow list does not yield a pop up warning.

**Comment by fikipollo** [comment]
As I understand, this error occurred when you close your session but the application was waiting for the response for some requests (e.g. a request saying "give me the list of invocations"). As the session has been closed, all requests will return an error --> message are shown.
I've fixed the issue, adding some error control logic and forcing the reload of the page after sign-out (will cancel automatically all the pending requests).

**Comment by fikipollo** [comment]
Added in v0.3
