### ISSUE TITLE
”New history ” button in History list view is positioned in an odd way compared to the refresh button. .

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#21]
”New history ” button in History list view is positioned in an odd way compared to the refresh button. .

**Comment by fikipollo** [comment]
I don't understand this issue 
Could you send me an screenshot? For me looks like this

![screenshot_2017-09-04_11-59-48](https://user-images.githubusercontent.com/11427394/30021735-aa86bf2c-9168-11e7-828d-7a34d8bb5b6a.png)

**Comment by TKlingstrom** [comment]
Now it is positioned as it should be, when I first used it the "new history" button was located blow and slightly to the left of the Refresh button.

**Comment by fikipollo** [comment]
Added in v0.3
