### ISSUE TITLE
The Yes/no format used by Galaxy is more clear than checkboxes for input parameters choices. 

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#22]
The Yes/no format used by Galaxy is more clear than checkboxes for input parameters choices.

**Comment by fikipollo** [comment]
Replaced by yes/no buttons
Added in v0.3

![screenshot_2017-09-06_11-27-33](https://user-images.githubusercontent.com/11427394/30104599-63ed2440-92f6-11e7-8c59-90504180b120.png)
