### ISSUE TITLE
Input parameters in checkbox listed are a bit awkward

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#23]
When selecting between modes (for example Choose computation mode in BamSummary) Galaksio displays a list of check boxes and then the fields dependent on your choice in the check boxes. In Galaxy you instead have a drop down menu of modes which puts the dependent fields in a more clear context (in Galaksio it looks like they are choices for the last option in the checkbox list).

**Comment by fikipollo** [comment]
Replaced checkboxes by a drop-down menu.
Added in v0.3
