### ISSUE TITLE
The outputs list is not clearly multiple choice. 

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#24]
The outputs list is not clearly multiple choice. It works well if you know that hold control and select all options you want is default but could be made clear with check boxes like in Galaxy.

**Comment by fikipollo** [comment]
@TKlingstrom  Could you give more details about this issue?

**Comment by TKlingstrom** [comment]
![multiple](https://user-images.githubusercontent.com/1171855/30213132-fa7bf334-94a7-11e7-9596-6e4e2c3be895.png)

**Comment by fikipollo** [comment]
Replaced multi-select fields by list of checkboxes

Added in v0.3
