### ISSUE TITLE
To agressive warning on input data

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#25]
At ”Input data” you immediately get the message ” Some of the required fields are not valid or are empty. Please check the form and try again!”

**Comment by fikipollo** [comment]
When do you get that message? always even if the data is loaded or when you try to continue with invalid data? Any proposal for the message?

**Comment by TKlingstrom** [comment]
The "Some of the required fields are not valid or are empty. Please check the form and try again!" is shown as soon as you reach step 3 "input selection". Chaning the warning message from

> Some of the required fields are not valid or are empty. Please check the form and try again!

to

> Some of the required fields are not valid or are empty. Please fill in all fields to continue.

Would make the text more appropriate within the context.

**Comment by fikipollo** [comment]
Changed. 
Added in v0.3
