### ISSUE TITLE
The “success” message when sending the workflow is a bit big and makes it look like the workflows i finished.

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#27]
The “success” message when sending the workflow is a bit big and makes it look like the workflows i finished.

**Comment by TKlingstrom** [comment]
After retesting see that it actually says that I am done despite not being done.

**Comment by fikipollo** [comment]
it was an problem when checking the invocation state, fixed and added new states (waiting in queue).
Added in v0.3
