### ISSUE TITLE
A partially successful workflow is listed as "failure" in Galaksio

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#28]
Running the Mouse ChIP-seq workflow one of the tools fail due to issues with the tool. This cause Galaksio to identify the Workflow as failed and when clicking "Lets look at the results" I am sent to the Home page on Galaksio rather than the results.

This mean that the results become inaccessible.

**Comment by fikipollo** [comment]
Fixed, now results are shown even if the workflow failed.

Added in v0.3
