### ISSUE TITLE
Can't select old history at the bottom of the second step of workflow invocation

### ISSUE THREAD

**Issue by yvanlebras** [SGBC/galaksio#44]
Dear @fikipollo 

Testing more deeply Galaksio, I just find that, if I have quite a lot of histories, I can't select bottom / old history on the second workflow invocation step "history selection". When I try to go down on the page, I can't (it seems this is stopping at the bottom of the content history so datasets at the right of the page). This appears in Firefox as Chrome...

**Comment by yvanlebras** [comment]
... The same occurs on galaksio/histories ...

**Comment by TKlingstrom** [comment]
This is now solved: 
See: https://github.com/OskarSLU/galaksio/commit/49f4a0afd37d748637c2584ef70b07a54ef1a5ba
https://github.com/OskarSLU/galaksio/commit/49f4a0afd37d748637c2584ef70b07a54ef1a5ba

**Comment by yvanlebras** [comment]
thanks !
